version: '3.3'
services:
  app_a2:
    container_name: fastapi-ml
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - 9000:9000
    volumes:
      - ./:/app/
      - ./app/static:/app/static
    # entrypoint: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 9000
  # jupyter_lab:
  #   container_name: jupyter_lab_test
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       INSTALL_DEV: ${INSTALL_DEV-true}
  #   ports:
  #     - 8888:8888
  #   entrypoint: jupyter lab --ip 0.0.0.0 --port=8888 --no-browser --allow-root
